// <auto-generated />
using System;
using AcademySystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcademySystem.Migrations
{
    [DbContext(typeof(ContextAcademy))]
    partial class ContextAcademyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcademySystem.Models.Professor", b =>
                {
                    b.Property<int>("CodigoProfessor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaminhoFoto")
                        .HasColumnName("_foto")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DescricaoFormacao")
                        .HasColumnName("_formacao")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DiaContratacao")
                        .HasColumnName("_contratacao")
                        .HasColumnType("Date");

                    b.Property<string>("Idade")
                        .HasColumnName("_idade")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MateriaSelecionada")
                        .HasColumnName("_materiaLecionada")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .HasColumnName("_nome")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Rg")
                        .HasColumnName("_rg")
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("Status")
                        .HasColumnName("_ativo")
                        .HasColumnType("bit");

                    b.Property<int>("sexo")
                        .HasColumnName("_sexo")
                        .HasColumnType("int");

                    b.HasKey("CodigoProfessor");

                    b.ToTable("tbl_Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
